// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace van_rental.Models;

public partial class Clients
{
    public int Id { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Tel { get; set; }

    public string Mail { get; set; }

    public virtual ICollection<Rentals> Rentals { get; set; } = new List<Rentals>();
}