// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace van_rental.Models
{
    public partial class GetRentalsInfosResult
    {
        public int rental_id { get; set; }
        public DateTime? departure_date { get; set; }
        public DateTime? return_date { get; set; }
        public int client_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int vehicle_id { get; set; }
        public string name { get; set; }
    }
}
