// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using van_rental.Models;

namespace van_rental.Models
{
    public partial class van_rentalContext
    {

        [DbFunction("CalculateRentalPrice", "dbo")]
        public static decimal? CalculateRentalPrice(DateTime? DepartureDate, DateTime? ReturnDate, decimal? PricePerDay)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
