// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace vanRental.Models;

public partial class VehicleModels
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string PictureUrl { get; set; }

    public int? GasTank { get; set; }

    public int? Pax { get; set; }

    public int? PricePerDay { get; set; }

    public virtual ICollection<Vehicles> Vehicles { get; set; } = new List<Vehicles>();
}